apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ro-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ro-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ro-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ro-cluster-role
subjects:
- kind: ServiceAccount
  name: ro-user
  namespace: default
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ro-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "ro-user"
